version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ambienet_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ambienet_production_postgres
    
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres


  pgadmin12:
    image: dpage/pgadmin4:latest
    hostname: pgadmin12
    #restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=santiago@mail.com"
      - "PGADMIN_DEFAULT_PASSWORD=santiago"
    ports:
      - "5050:80"
    #volumes:
     # - ../volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    