# Generated by Django 3.2.3 on 2021-06-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201117_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'entidad'), (2, 'sensor_social'), (3, 'usuario_regular')], default=3, null=True),
        ),
    ]
