# Generated by Django 3.2.3 on 2021-07-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rolerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'pending'), (2, 'rejected'), (3, 'approved')], default=1, null=True),
        ),
    ]
