# Generated by Django 3.2.3 on 2021-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rolerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='punctuation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quantity_reported_posts',
            field=models.IntegerField(default=0),
        ),
    ]
