# Generated by Django 3.2.3 on 2021-08-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('climatic_phenomenon', models.CharField(max_length=25)),
                ('time_interval', models.CharField(max_length=25)),
                ('temp_max', models.FloatField(default=0.0)),
                ('temp_min', models.FloatField(default=0.0)),
                ('conditions_can_be_triggered', models.CharField(max_length=255)),
                ('associated_risks', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('COM', 'common'), ('ADV', 'advanced')], default='COM', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='advanced_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.advancedreport'),
        ),
    ]
