# Generated by Django 3.2.3 on 2021-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210819_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='validator_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
