# Generated by Django 3.2.7 on 2021-09-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210926_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_catastrophe',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
