# Generated by Django 3.2.7 on 2021-09-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_type_catastrophe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_report',
            field=models.CharField(blank=True, choices=[('COM', 'common'), ('ADV', 'advanced')], max_length=4),
        ),
    ]
