# Generated by Django 3.2.9 on 2021-11-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_type_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedreport',
            name='affected_people',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='advancedreport',
            name='affected_species',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
